language: node_js
node_js:
  - "8.2.1"
jdk:
  - oraclejdk8
cache:
  directories:
  - $HOME/.m2
jobs:
  include:
    - stage: CI CD For WSO2 API Cloud 
      install:
      - npm install newman
      script:
      - bash BackendServiceImpl/build.sh 
      - bash DeployBackendService/deploy.sh Dev
      - echo "Development API Runtime"
      - node_modules/.bin/newman run DeployAPI/WSO2_API_PUBLISHER.postman_collection.json -e DevEnvironment/Development.postman_environment.json --global-var username=$clouduser --global-var password=$clouduserpass
      - node_modules/.bin/newman run TestAPI/WSO2_API_STORE_TESTS.postman_collection.json -e DevEnvironment/Development.postman_environment.json --global-var username=$clouduser --global-var password=$clouduserpass
#      - echo "Staging API Runtime"
#      - node_modules/.bin/newman run WSO2_API_PUBLISHER.postman_collection.json -e Staging.postman_environment.json --global-var username=$staging-clouduser --global-var password=$staging-clouduserpass 
#      - echo "Production API Runtime"
#      - node_modules/.bin/newman run WSO2_API_PUBLISHER.postman_collection.json -e Production.postman_environment.json --global-var username=$production-clouduser --global-var password=$production-clouduserpass 
